# This is a basic workflow to help you get started with Actions

name: CI

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    
      - uses: msys2/setup-msys2@e9898307ac31d1a803454791be09ab9973336e1c
        with:
          msystem: MINGW64
          path-type: minimal
          update: true
          install: >-
            mingw-w64-x86_64-qt6-static
            mingw-w64-x86_64-qt6-svg
            mingw-w64-x86_64-qt6-base
            mingw-w64-x86_64-libwebp
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-openssl
            zip
            
      - name: Configure
        shell: msys2 {0}
        run: |
          export PATH="/mingw64/bin:$PATH"
          export PATH="/mingw64/qt6-static/bin:$PATH"
          cmake -B build -GNinja -DCMAKE_INSTALL_PREFIX=inst -DQT_DEBUG_FIND_PACKAGE=ON

      - name: Build
        shell: msys2 {0}
        run: |
          export PATH="/mingw64/bin:$PATH"
          export PATH="/mingw64/qt6-static/bin:$PATH"
          cmake --build build

      - name: Package
        shell: msys2 {0}
        run: |
          export PATH="/mingw64/bin:$PATH"
          export PATH="/mingw64/qt6-static/bin:$PATH"
          cd build && cpack
          
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          archive: false
          path: "build/dist/dsda-launcher-*.zip"

      - name: Release
        if: ${{ contains(github.ref, 'tags') }}
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd
        with:
          name: ${{ github.ref_name }}
          allowUpdates: true
          artifacts: src/build/dsda-launcher-${{ github.ref_name }}-win64.dmg
          
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      
      - name: Install Qt
        uses: jurplel/install-qt-action@48d3ad6db93f3627c8ee7a0454bc6f3744f7e730
        with:
          version: '6.8.*'
          host: 'linux'
          target: 'desktop'
          arch: 'linux_gcc_64'
          tools: 'tools_opensslv3_src'

      - name: Install required packages
        run: |
          sudo apt install libfuse2

      - name: Configure
        run: |
          cmake -B build -GNinja

      - name: Build
        run: |
          cmake --build build

      - name: Package
        run: |
          cd build && cpack

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          archive: false
          path: "build/dist/*.AppImage"

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          archive: false
          path: "build/dist/dsda-launcher-*.tar.gz"

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          archive: false
          path: "build/dist/*.deb"

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install Qt
        uses: jurplel/install-qt-action@48d3ad6db93f3627c8ee7a0454bc6f3744f7e730
        with:
          version: '6.11.*'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'

      - name: Configure
        run: |
          # Universal binaries need Xcode rather than Ninja
          cmake -B build -GXcode -DCMAKE_INSTALL_PREFIX=inst

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Package
        run: |
          cmake --install build
          cd build && cpack

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          archive: false
          path: "build/dist/dsda-launcher-*.dmg"
    
      - name: Release
        if: ${{ contains(github.ref, 'tags') }}
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd
        with:
          name: ${{ github.ref_name }}
          allowUpdates: true
          artifacts: src/build/dsda-launcher-${{ github.ref_name }}-mac.dmg
